#!/bin/bash

set -euo pipefail

remove_oldest()
{
    ls -1tp *.sql | tail -n +6 | xargs -I {} rm -- {}
    ls -1tpd v* | tail -n +6 | xargs -I {} rm -r -- {}
}

version=${1-$(wget -O - -q https://api.github.com/repos/Chocobozzz/PeerTube/releases/latest | jq --raw-output .tag_name)}

echo "Update to $version"

pg_dump peertube > peertube-pre-$version.sql

if [[ ! -d "$version" ]]
then
    wget --continue https://github.com/Chocobozzz/PeerTube/releases/download/$version/peertube-$version.zip
    unzip peertube-$version.zip
    rm peertube-$version.zip
    mv peertube-$version $version
fi

cd $version
pnpm install --frozen-lockfile --production
cd ..
diff --color -u $version/config/production.yaml.example config/production.yaml || echo
diff --color -u $version/support/systemd/peertube.service /etc/systemd/system/peertube.service || echo
ln --no-target-directory --force --symbolic $version current
sudo systemctl restart peertube
sudo systemctl reload apache2

remove_oldest
