#!/bin/bash

set -euo pipefail

remove_oldest()
{
    ls -1tp *.sql | tail -n +6 | xargs -I {} rm -- {}
    ls -1tpd v* | tail -n +6 | xargs -I {} rm -r -- {}
}

version=${1-$(wget -O - -q https://api.github.com/repos/Chocobozzz/PeerTube/releases/latest | jq --raw-output .tag_name)}

echo "Update to $version"

pg_dump peertube > peertube-pre-$version.sql
wget --continue https://github.com/Chocobozzz/PeerTube/releases/download/$version/peertube-$version.zip
unzip peertube-$version.zip
rm peertube-$version.zip
mv peertube-$version $version
cd $version
yarn install --production --pure-lockfile
cd ..
git merge-file -p config/production.yaml current/config/production.yaml.example $version/config/production.yaml.example | tee production.yaml.new
git merge-file -p /etc/systemd/system/peertube.service current/support/systemd/peertube.service $version/support/systemd/peertube.service | tee peertube.service.new
ln --no-target-directory --force --symbolic $version current
sudo systemctl restart peertube
sudo systemctl reload apache2

remove_oldest
