#!/bin/bash

set -euo pipefail

version=${1-$(wget -O - -q https://api.github.com/repos/roundcube/roundcubemail/releases/latest | jq --raw-output .tag_name)}

git fetch
git stash
git checkout $version
git stash pop
php ~/.local/bin/composer update --no-dev -a --no-scripts
bin/install-jsdeps.sh
bin/jsshrink.sh
bin/updatecss.sh
bin/cssshrink.sh
cd skins/elastic
./node_modules/.bin/lessc --clean-css="--s1 --advanced" styles/styles.less > styles/styles.css
./node_modules/.bin/lessc --clean-css="--s1 --advanced" styles/print.less > styles/print.css
./node_modules/.bin/lessc --clean-css="--s1 --advanced" styles/embed.less > styles/embed.css
cd -
php ./bin/update.sh -v $version
