#!/bin/bash

set -euo pipefail

version=${1-$(wget -O - -q https://api.github.com/repos/roundcube/roundcubemail/releases/latest | jq --raw-output .tag_name)}

git fetch
git stash
git checkout $version
git stash pop
composer update --no-dev -a --no-scripts
bin/install-jsdeps.sh
cd skins/elastic
lessc -x styles/styles.less > styles/styles.css
lessc -x styles/print.less > styles/print.css
lessc -x styles/embed.less > styles/embed.css
cd -
./bin/update.sh -v $version
