#!/bin/bash

set -euo pipefail

version=$1

cd /usr/local/bin

wget https://github.com/rustic-rs/rustic/releases/download/$version/rustic-$version-x86_64-unknown-linux-gnu.tar.gz -O - | tar xz rustic
