#!/bin/bash

set -e

main()
{
    sudo systemctl stop uwsgi

    git fetch
    git rebase origin/master

    pipenv update
    ln --no-target-directory --symbolic --force $(pipenv --venv) venv

    sudo systemctl start uwsgi
}

main
