#!/bin/bash

set -e

main()
{
    local version=$1

    sudo systemctl stop uwsgi

    git fetch
    git stash
    git checkout $version
    git stash pop

    . venv/bin/activate
    pip install --upgrade --requirement requirements.txt

    sudo systemctl start uwsgi
}

main $@
