#!/bin/sh

set -e

source "$(dirname $(realpath $BASH_SOURCE))/config/backup.sh"

readonly LOCK="/var/lock/backup"
readonly MOUNT_POINT=$(dirname $REPOSITORY)

function postgresql_get_databases()
{
    sudo -u postgres psql --pset tuples_only --command 'SELECT datname FROM pg_database WHERE datistemplate = false;'
}

function postgresql_test()
{
    readonly CLUSTER_DIR="/var/lib/postgresql/$PGSQL_VERSION/backup"
    readonly TEST_DIR="$CLUSTER_DIR/tests"

    sudo -u postgres pg_createcluster "$PGSQL_VERSION" backup -d "$CLUSTER_DIR"
    sudo -u postgres pg_conftool "$PGSQL_VERSION" backup set shared_preload_libraries 'pg_stat_statements,powa,pg_stat_kcache,pg_qualstats'
    sudo -u postgres pg_ctlcluster "$PGSQL_VERSION" backup start
    sudo -u postgres psql --port 5433 --command "CREATE ROLE $PGSQL_USER WITH SUPERUSER PASSWORD '$PGSQL_PASSWORD'"

    for database in $(postgresql_get_databases)
    do
        if [[ "$database" != "powa" && "$database" != "postgres" ]]
        then
            sudo -u postgres psql --port 5433 --output /dev/null --quiet --command "CREATE DATABASE $database;"
            sudo -u postgres psql --port 5433 --output /dev/null --quiet --command "\i /media/data/pgsql_dump/$database.dump" "$database"
        fi
    done

    sudo -u postgres pg_ctlcluster --mode fast "$PGSQL_VERSION" backup stop
    sudo -u postgres pg_dropcluster "$PGSQL_VERSION" backup
}

function postgersql_backup()
{
    if [[ ! -d "/media/data/pgsql_dump/" ]]
    then
        sudo mkdir --parent "/media/data/pgsql_dump/"
        sudo chown postgres:postgres "/media/data/pgsql_dump/"
    fi

    for database in $(postgresql_get_databases)
    do
        sudo -u postgres pg_dump --file "/media/data/pgsql_dump/$database.dump" "$database"
    done
}

function main()
{
    mount | grep -q $MOUNT_POINT || mount $MOUNT_POINT

    mysqldump -u $MYSQL_USER --password="$MYSQL_PASSWORD" --all-databases > /media/data/mysql.dump
    postgersql_backup

    borg create --compression zlib,6 --exclude-from "$(dirname $(realpath $BASH_SOURCE))/config/exclude.txt" "$REPOSITORY::cuddles-$(date +%Y-%m-%d_%H:%M:%S)" $BACKUP_FILES

    borg prune --verbose --stats --list \
        --keep-daily=7 --keep-weekly=4 --keep-monthly=-1 \
        "$REPOSITORY"

    if [[ $(date +%H) -eq 3 ]]
    then
        rsync --recursive --delete --compress $REPOSITORY kimsufi:~ &
        readonly RSYNC_PID=$!
    fi

    set +e
    postgresql_test
    echo "postgresql backup ok"
    set -e

    wait $RSYNC_PID
    echo "remote backup ok"

    umount $MOUNT_POINT
}

if [[ ! -f "$LOCK" ]]
then
    touch "$LOCK"
    trap 'rm -f "$LOCK"' EXIT
    main
fi
