#!/bin/sh

set -euo pipefail

readonly ZONEDIR='/var/cache/bind'

main()
{

    local zone=$1
    local zonefile="$ZONEDIR/$zone.zone"

    named-checkzone $zone $zonefile.signed

    local oldserial=$(named-checkzone $zone $zonefile | egrep -ho '[0-9]{10}')
    local newserial=$(date +%Y%m%d%H)

    if [ "$newserial" -lt "$oldserial" ]
    then
        local diff=$(($oldserial-$newserial))
        newserial=$(($newserial+$diff+1))
    fi

    sed -i 's/'$oldserial'/'$(($newserial+1))'/' $zonefile

    echo "old serial: $oldserial"
    echo "new serial: $newserial"

    dnssec-signzone -A -3 $(head -c 1000 /dev/random | sha1sum | cut -b 1-16) -N increment -o $zone -t $zonefile
    service bind9 reload
    named-checkzone $zone $zonefile.signed
}

main $*
