#!/bin/bash

set -euo pipefail

source "$(dirname $(realpath $BASH_SOURCE))/config/current.sh"

function main() {
    export CARGO_TERM_COLOR=always
    export FORCE_COLOR=true

    if [ -z "$SSH_ORIGINAL_COMMAND" ]
    then
        find $REPOSITORIES_DIR -type d -name '*.git' | sed "s#$REPOSITORIES_DIR/\?##" | sed 's#\.git$##' | sort
        exit 0
    fi

    local command=$(echo $SSH_ORIGINAL_COMMAND | grep -Po '^git-[^\s]*')

    if [ "$command" = "git-create-repo" -o "$command" = "git-deploy" -o "$command" = "git-repo" ]
    then
        $SSH_ORIGINAL_COMMAND
    else
        local repo=$(echo $SSH_ORIGINAL_COMMAND | grep -Po "'.*'$" | tr -d "'")

        $command "$REPOSITORIES_DIR/$repo"
    fi
}

main "$@"
