#!/bin/bash

set -e

readonly BASE_DIR="$(dirname $(realpath $BASH_SOURCE))"

source "$BASE_DIR/config/current.sh"

function createRepo()
{
    local name=$1
    local repo="$REPOSITORIES_DIR/$name.git"

    git init -q --bare "$repo"

    echo "$repo"
}

function createGithubMirror()
{
    local repo=$1
    local name=${2/\//-}
    local visibility=$3

    local private=$(test $visibility = "public" && echo 'true' || echo 'false')

    cd "$repo"
    echo -n "Create $visibility github mirror: "
    curl -s -u "$GITHUB_USER:$GITHUB_TOKEN" https://api.github.com/user/repos -d '{"name":"'$name'", "private":"'$private'", "visibility":"'$visibility'"}' > /dev/null
    if [[ $? -eq 0 ]]
    then
        git remote add github "git@github.com:$GITHUB_USER/$name.git"
        echo 'ok'
    else
        echo 'failed'
    fi
}

function createGitlabMirror()
{
    local repo=$1
    local name=${2/\//-}
    local visibility=$3
    local visibility_level=0

    cd "$repo"

    echo -n "Create $visibility gitlab mirror: "
    curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" -d "name=$name" -d "visibility=$visibility" https://gitlab.com/api/v4/projects > /dev/null
    if [[ $? -eq 0 ]]
    then
        git remote add gitlab "git@gitlab.com:$GITLAB_USER/$name.git"
        echo 'ok'
    else
        echo 'failed'
    fi
}

function installHooks()
{
    local repo=$1

    cd "$repo/hooks"
    ln -s "$PUBLIC_REPOSITORIES_DIR/deploy/current/src/hooks/post-receive"
}

function main()
{
    local name="$1"
    local visibility="${2-private}"
    local repo=$(createRepo "$name")

    createGithubMirror "$repo" "$name" "$visibility"
    createGitlabMirror "$repo" "$name" "$visibility"

    installHooks "$repo"

    echo "git@$GIT_DOMAIN:$name.git"
}

if [[ $# -lt 1 ]]
then
    echo "$0 name [visibility]"
    exit 1
fi

main "$@"
