#!/bin/bash

set -e

source "$(dirname $(realpath $BASH_SOURCE))/config/current.sh"

function main()
{
    local command=$(echo $SSH_ORIGINAL_COMMAND | grep -Po 'git-[^\s]*')

    if [ "$command" = "git-create-repo" ]
    then
        $SSH_ORIGINAL_COMMAND
    else
        local repo=$(echo $SSH_ORIGINAL_COMMAND | grep -Po "'.*'$" | tr -d "'")

        $command "$REPOSITORIES_DIR/$repo"
    fi
}

main "$@"
