#!/bin/sh

set -e

readonly LOCK="/var/lock/vps-sync"

if [ ! -f "$LOCK" ]
then
    touch "$LOCK"
    trap 'rm -f "$LOCK"' EXIT
    rsync --archive --recursive --compress --delete --delete-after kimsufi:~/torrents/ /media/data/torrent
fi
